apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: prod
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: joinpickup/web:$TAG
      envFrom:
        - secretRef:
            name: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: prod
spec:
  ports:
  - port: 3000
  selector:
    app: web
