apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v3
  namespace: prod
  labels:
    app: web-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-v3
  template:
    metadata:
      labels:
        app: web-v3
    spec:
      containers:
        - name: web-v3
          image: joinpickup/web:$TAG
---
apiVersion: v1
kind: Service
metadata:
  name: web-v3
  namespace: prod
spec:
  ports:
    - port: 3000
  selector:
    app: web-v3
